### ISSUE TITLE
kubernetes에서 LoadBalancer 서비스의 external-ip가 pending으로 나타나는 현상

### ISSUE THREAD

**Issue by ndiepray** [ndiepray/CCCR_FLFD#7]
## 이슈
외부에서 grafana에 접속하기 위해 grafana 서비스를 loadbalancer 타입으로 외부에 노출시키려는 과정에서 LoadBalancer 서비스의 external-ip가 pending으로 나타남
![image](https://user-images.githubusercontent.com/86943561/129227171-58bd18ce-24da-44d6-869f-47bfb55fefa0.png)

## 해결
자체적으로 vm에 k8s cluster를 구축한 경우 loadbalancer 서비스를 사용하려면 MetalLB을 이용해 쿠버네티스 리소스로 loadbalancer 기능을 제공해야 한다.
- 즉, 클라우드의 관리형 k8s 서비스 및 MetalLB를 사용하지 않으면 external loadbalancer가 프로비저닝 되지 않는다.
```
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml
```
- metallb-config.yaml 작성 후 생성
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.100.200-192.168.100.209
```
![image](https://user-images.githubusercontent.com/86943561/129228435-39ec70b4-0212-4069-86ef-d1ece4075d2c.png)
