### ISSUE TITLE
[이슈] grafana 대쉬보드에 node 하나만 monitoring되는 현상

### ISSUE THREAD

**Issue by ndiepray** [ndiepray/CCCR_FLFD#9]
### 이슈
현재 grafana 대쉬보드에서는 telegraf pod가 동작하는 node 하나의 metric 사용량만 monitoring 되는데 모든 node의 metric을 monitoring 할 수 있도록 수정
![image](https://user-images.githubusercontent.com/86943561/129238899-6dfb15b3-01ce-40e9-b098-923e50e45ffd.png)

### 해결
1) 각 node마다 label 추가
```
kubectl label nodes kube-control key=control
kubectl label nodes kube-node1 key=node1
kubectl label nodes kube-node2 key=node2
kubectl label nodes kube-node3 key=node3
kubectl get nodes --show-labels
```
2) 각 노드별 deployment 오브젝트 생성
deployment 생성 시 nodeSelector 옵션에 pod가 실행될 노드의 label을 지정하여 deployment 4개 생성
``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
...
...
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
      nodeSelector:
        key: control
```
3) deployment를 위한 service 생성
deployment 마다 service가 필요
```
kubectl expose deployment telegraf --type=NodePort --port=8125 --target-port=8125 --protocol=UDP 
kubectl expose deployment telegraf1 --type=NodePort --port=8125 --target-port=8125 --protocol=UDP 
kubectl expose deployment telegraf2 --type=NodePort --port=8125 --target-port=8125 --protocol=UDP 
kubectl expose deployment telegraf3 --type=NodePort --port=8125 --target-port=8125 --protocol=UDP
```
4) Kubernetes Control-Plane Node Taint 설정
Pod 상태 확인 시 node가 control-plane로 지정되어 생성 된 pod는 Pending 상태로 지속 -> control-plane은 Taint 설정을 해준다.
- taint 형식: kubectl taint node {nodename} {key}={value}:{option}
- control plane의 taint를 확인하여 설정을 해제하고 pod가 running 상태가 되면 다시 pod를 못 올리도록 설정
![image](https://user-images.githubusercontent.com/86943561/129487236-fc5c72de-824a-49da-b3b9-9a6be056eb2c.png)
![image](https://user-images.githubusercontent.com/86943561/129487769-5f3f2dc7-3ef1-441a-a735-5637933e9223.png)

5) 대쉬보드 확인
![image](https://user-images.githubusercontent.com/86943561/129487309-4298c826-9e0e-4286-b3c1-979e13fe8916.png)
